//! Execution-level parity against the production Java League Rating.
//!
//! `tests/golden/league-rating-v41.json` is generated by
//! `replay-engine/tests/java-golden/RatingGoldenDumper.java`, which runs the real
//! `com.wotb.core.league.LeagueRatingCalculator` (V4.1) + `LeagueBatchRatingCalculator` (V6) over
//! deterministic synthetic battles and emits both the inputs and the production outputs.
//!
//! CI has no Java toolchain, so this committed golden is what makes Rating parity (the merge
//! blocker) continuously verifiable: any divergence in weights, caps, normalization, tie-breaks or
//! batch projection fails here with the offending field.

use std::fs;

use replay_core::rating::{
    finite_positive, global_index, observed_mean, player_batch_rating, rate_battle,
    team_batch_rating, team_index, wilson_lower_bound, RatingPlayer,
};
use serde::Deserialize;

mod common;

use common::{assert_close, golden_path};

#[derive(Debug, Deserialize)]
struct Golden {
    scenarios: Vec<Scenario>,
    batch: Vec<NamedValue>,
    normalizer: Vec<NamedValue>,
}

#[derive(Debug, Deserialize)]
struct NamedValue {
    name: String,
    value: Option<f64>,
}

#[derive(Debug, Deserialize)]
struct Scenario {
    name: String,
    #[serde(rename = "winnerTeam")]
    winner_team: i64,
    players: Vec<InputPlayer>,
    expected: Expected,
}

#[derive(Debug, Deserialize)]
struct InputPlayer {
    #[serde(rename = "accountId")]
    account_id: String,
    team: i64,
    #[serde(rename = "damageDealt")]
    damage_dealt: i64,
    #[serde(rename = "damageAssisted")]
    damage_assisted: i64,
    #[serde(rename = "damageBlocked")]
    damage_blocked: i64,
    #[serde(rename = "damageReceived")]
    damage_received: i64,
    kills: i64,
    shots: i64,
    #[serde(rename = "hitsDealt")]
    hits_dealt: i64,
    #[serde(rename = "penetrationsDealt")]
    penetrations_dealt: i64,
    survived: bool,
    #[serde(rename = "lifeTimeSec")]
    life_time_sec: Option<f64>,
}

#[derive(Debug, Deserialize)]
struct Expected {
    players: Vec<ExpectedPlayer>,
    teams: Vec<ExpectedTeam>,
    #[serde(rename = "mvpAccountId")]
    mvp_account_id: Option<String>,
}

#[derive(Debug, Deserialize)]
struct ExpectedPlayer {
    #[serde(rename = "accountId")]
    account_id: String,
    dimensions: Vec<f64>,
    preliminary: f64,
    #[serde(rename = "baseRating")]
    base_rating: f64,
    #[serde(rename = "finalRating")]
    final_rating: f64,
    #[serde(rename = "survivalState")]
    survival_state: String,
    mvp: bool,
    #[serde(rename = "teamBest")]
    team_best: bool,
}

#[derive(Debug, Deserialize)]
struct ExpectedTeam {
    team: i64,
    rating: f64,
    #[serde(rename = "dimensionAverages")]
    dimension_averages: Vec<f64>,
    #[serde(rename = "bestAccountId")]
    best_account_id: Option<String>,
}

fn golden() -> Golden {
    let path = golden_path();
    let raw = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read golden {}: {e}", path.display()));
    serde_json::from_str(&raw).expect("golden is valid JSON")
}

fn to_rating_player(input: &InputPlayer) -> RatingPlayer {
    RatingPlayer {
        account_id: input.account_id.clone(),
        nickname: None,
        clan: None,
        team: input.team,
        damage_dealt: input.damage_dealt,
        damage_assisted: input.damage_assisted,
        damage_blocked: input.damage_blocked,
        damage_received: input.damage_received,
        kills: input.kills,
        shots: input.shots,
        hits_dealt: input.hits_dealt,
        penetrations_dealt: input.penetrations_dealt,
        survived: input.survived,
        settlement_life_time_sec: input
            .life_time_sec
            .map(|seconds| seconds.round() as i64)
            .filter(|seconds| *seconds != 0),
    }
}

#[test]
fn rating_matches_the_java_golden_scenario_by_scenario() {
    let golden = golden();
    assert!(
        golden.scenarios.len() >= 10,
        "golden must cover several scenarios"
    );

    for scenario in &golden.scenarios {
        let players: Vec<RatingPlayer> = scenario.players.iter().map(to_rating_player).collect();
        let rating = rate_battle(&scenario.name, scenario.winner_team, &players);

        assert_eq!(
            rating.players.len(),
            scenario.expected.players.len(),
            "{}: player count",
            scenario.name
        );
        for expected in &scenario.expected.players {
            let actual = rating
                .players
                .iter()
                .find(|p| p.account_id == expected.account_id)
                .unwrap_or_else(|| panic!("{}: missing {}", scenario.name, expected.account_id));
            let label = format!("{} / {}", scenario.name, expected.account_id);
            assert_eq!(actual.dimensions.len(), expected.dimensions.len());
            for (position, expected_dimension) in expected.dimensions.iter().enumerate() {
                assert_close(
                    actual.dimensions[position],
                    *expected_dimension,
                    &format!("{label} dimension[{position}]"),
                );
            }
            assert_close(
                actual.preliminary,
                expected.preliminary,
                &format!("{label} preliminary"),
            );
            assert_close(
                actual.base_rating,
                expected.base_rating,
                &format!("{label} base"),
            );
            assert_close(
                actual.final_rating,
                expected.final_rating,
                &format!("{label} final"),
            );
            assert_eq!(
                actual.survival_state.code(),
                expected.survival_state,
                "{label} survival state"
            );
            assert_eq!(actual.mvp, expected.mvp, "{label} mvp flag");
            assert_eq!(
                actual.team_best, expected.team_best,
                "{label} team-best flag"
            );
        }

        for expected_team in &scenario.expected.teams {
            let actual = rating
                .teams
                .iter()
                .find(|t| t.team == expected_team.team)
                .unwrap_or_else(|| {
                    panic!("{}: missing team {}", scenario.name, expected_team.team)
                });
            let label = format!("{} / team {}", scenario.name, expected_team.team);
            assert_close(
                actual.rating,
                expected_team.rating,
                &format!("{label} rating"),
            );
            for (position, expected_average) in expected_team.dimension_averages.iter().enumerate()
            {
                assert_close(
                    actual.dimension_averages[position],
                    *expected_average,
                    &format!("{label} dimension average[{position}]"),
                );
            }
            assert_eq!(
                actual.best_account_id, expected_team.best_account_id,
                "{label} best account"
            );
        }

        assert_eq!(
            rating.mvp_account_id, scenario.expected.mvp_account_id,
            "{}: mvp account",
            scenario.name
        );
    }
}

#[test]
fn batch_projection_matches_the_java_golden() {
    let golden = golden();
    for row in &golden.batch {
        let actual = match row.name.as_str() {
            "player" => player_batch_rating(1000.0, 1).expect("valid aggregate"),
            "player-none" => player_batch_rating(0.0, 0).expect("valid aggregate"),
            "team" => team_batch_rating(1000.0, 1).expect("valid aggregate"),
            "observed-mean" => observed_mean(1500.0, 3).expect("valid aggregate"),
            other => panic!("unexpected golden batch row {other}"),
        };
        match (actual, row.value) {
            (None, None) => {}
            (Some(actual), Some(expected)) => {
                assert_close(actual, expected, &format!("batch {}", row.name))
            }
            (actual, expected) => panic!(
                "batch {}: expected {:?}, got {:?}",
                row.name, expected, actual
            ),
        }
    }
}

#[test]
fn normalizer_matches_the_java_golden() {
    let golden = golden();
    for row in &golden.normalizer {
        let actual = match row.name.as_str() {
            "wilson-1-1" => wilson_lower_bound(1.0, 1.0),
            "wilson-10-20" => wilson_lower_bound(10.0, 20.0),
            "team-index-average" => team_index(1000.0, 1000.0),
            "trade-window-sec" => replay_core::rating::TRADE_AFTER_DEATH_WINDOW_SEC,
            other => panic!("unexpected golden normalizer row {other}"),
        };
        let expected = row.value.expect("normalizer values are finite");
        assert_close(actual, expected, &format!("normalizer {}", row.name));
    }

    // Independent invariants of the rank index (not covered by the golden rows).
    assert_eq!(global_index(100.0, &[100.0, 90.0]), 1.0);
    assert_eq!(global_index(0.0, &[100.0]), 0.0);
    assert!(finite_positive(1.0) && !finite_positive(0.0));
}
