FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /build
COPY java/settings-docker.xml settings.xml
# Keycloak custom Identity Providers: Wargaming.net and the official QQ provider.
# All provider sources are vendored; builds and runtime never download provider code.
COPY keycloak-qq-provider/pom.xml keycloak-qq-provider/pom.xml
COPY keycloak-qq-provider/src keycloak-qq-provider/src
COPY keycloak-wargaming-provider/pom.xml keycloak-wargaming-provider/pom.xml
COPY keycloak-wargaming-provider/src keycloak-wargaming-provider/src
RUN mvn -s settings.xml -f keycloak-qq-provider/pom.xml -DskipTests clean package -q
RUN mvn -s settings.xml -f keycloak-wargaming-provider/pom.xml -DskipTests clean package -q

FROM quay.io/keycloak/keycloak:26.6.4
ARG BUILD_COMMIT=unknown
ENV WOTBTOOLS_BUILD_COMMIT=${BUILD_COMMIT}
COPY --from=build /build/keycloak-qq-provider/target/keycloak-qq-provider.jar /opt/keycloak/providers/
COPY --from=build /build/keycloak-wargaming-provider/target/keycloak-wargaming-provider.jar /opt/keycloak/providers/

# WotBTools custom login theme (V8 Unified Layout)
COPY docker/keycloak/themes/wotbtools /opt/keycloak/themes/wotbtools
RUN /opt/keycloak/bin/kc.sh build \
  --db=postgres

COPY docker/keycloak/wotbtools-entrypoint.sh /opt/keycloak/bin/wotbtools-entrypoint.sh
ENTRYPOINT ["/bin/sh", "/opt/keycloak/bin/wotbtools-entrypoint.sh"]
