-- V10: in-site user notifications.
-- Payload stays JSON text; API turns it into key/value data for frontend i18n rendering.
create table user_notification (
    id               bigint generated by default as identity primary key,
    keycloak_user_id varchar(64) not null,
    type             varchar(64) not null,
    subject_type     varchar(32),
    subject_id       bigint,
    payload          text not null default '{}',
    read_at          timestamp with time zone,
    created_at       timestamp with time zone not null default now()
);

create index idx_user_notification_user_created
    on user_notification(keycloak_user_id, created_at desc);

create index idx_user_notification_user_unread
    on user_notification(keycloak_user_id)
    where read_at is null;
