-- 名人堂管理操作审计（只读；第一版 DELETE_ENTRY 快照）。
-- 与删除记录同一事务（audit 失败 → 记录不删；记录删除失败 → 无假审计）。
-- record hard delete 后原记录已不存在，快照必须完整落库（不能只存 record_id FK）。
create table hall_of_fame_admin_log (
    id bigint generated by default as identity primary key,

    action varchar(32) not null default 'DELETE_ENTRY',

    record_id bigint not null,
    arena_id varchar(32) not null,
    account_id bigint not null,
    nickname varchar(100) not null,
    tank_id bigint not null,
    tank_name varchar(100) not null,
    damage_dealt integer not null,
    battle_type varchar(16) not null,
    arena_bonus_type integer not null,
    replay_hash varchar(64),

    admin_keycloak_user_id varchar(64) not null,
    admin_username varchar(128),

    created_at timestamp with time zone not null default now()
);

create index idx_hall_of_fame_admin_log_created_at
    on hall_of_fame_admin_log (created_at desc);

create index idx_hall_of_fame_admin_log_record_id
    on hall_of_fame_admin_log (record_id);
