-- 名人堂「百场」排行榜 submission（单表承载完整生命周期：PENDING/CURRENT/SUPERSEDED/REJECTED/CANCELLED/DELETED）。
-- 业务规则见 docs/current-plan.md（百场）：
--   * user + vehicle 最多一个 active PENDING（partial unique index）
--   * user + vehicle 最多一个 CURRENT（partial unique index）
--   * 身份/成绩快照在创建时冻结；claimed 与 approved 两套数据同时保留，排行榜只读 approved*
--   * proof_screenshot 为临时私有审核资产（base64 data URL，同 Boost Apply 模式），
--     审核终态（APPROVE/REJECT/CANCEL）事务内清空，不永久保存
--   * replay 文件不落库：创建时解析校验后即丢弃（Spring multipart 临时文件自动清理）
create table hundred_battle_submission
(
    id                       bigint generated by default as identity primary key,

    user_keycloak_id         varchar(64)              not null,
    vehicle_id               bigint                   not null,
    vehicle_name             varchar(100)             not null,

    game_account_id_snapshot bigint                   not null,
    nickname_snapshot        varchar(100)             not null,

    claimed_average_damage   integer                  not null,
    claimed_battle_count     integer                  not null,

    approved_average_damage  integer,
    approved_battle_count    integer,

    status                   varchar(16)              not null default 'PENDING',

    proof_screenshot         text,

    replay_parse_ok          boolean                  not null default true,
    replay_game_id_match     boolean                  not null default true,
    replay_vehicle_match     boolean                  not null default true,
    replay_distinct_battles  boolean                  not null default true,

    submitted_at             timestamp with time zone not null default now(),
    approved_at              timestamp with time zone,
    approved_by              varchar(64),

    rejected_at              timestamp with time zone,
    rejected_by              varchar(64),
    reject_reason            varchar(64),
    reject_reason_text       varchar(500),

    cancelled_at             timestamp with time zone,

    deleted_at               timestamp with time zone,
    deleted_by               varchar(64),
    delete_reason            varchar(64),
    delete_reason_text       varchar(500),

    constraint ck_hundred_battle_submission_status
        check (status in ('PENDING', 'CURRENT', 'SUPERSEDED', 'REJECTED', 'CANCELLED', 'DELETED'))
);

-- user + vehicle 最多一个 active PENDING（PostgreSQL partial unique index；JPA validate 不校验索引）
create unique index uk_hundred_battle_pending_user_vehicle
    on hundred_battle_submission (user_keycloak_id, vehicle_id) where status = 'PENDING';

-- user + vehicle 最多一个 CURRENT
create unique index uk_hundred_battle_current_user_vehicle
    on hundred_battle_submission (user_keycloak_id, vehicle_id) where status = 'CURRENT';

-- 公开排行榜查询：vehicle × CURRENT，按 approved_average_damage DESC → approved_at ASC → id ASC
create index idx_hundred_battle_query
    on hundred_battle_submission (vehicle_id, status, approved_average_damage desc, approved_at, id);

-- 管理后台按状态查询
create index idx_hundred_battle_submission_status
    on hundred_battle_submission (status, submitted_at desc);

-- 个人中心按用户查询
create index idx_hundred_battle_submission_user
    on hundred_battle_submission (user_keycloak_id, status, submitted_at desc);
