-- 名人堂「百场」回放审核证据（V19）：PENDING submission 的原始 5 个 .wotbreplay 元数据。
-- 物理文件由 HallOfFameReplayStorage 内容寻址存储（baseDir/{sha256}.wotbreplay，复用 wotb.hof.replay-dir），
-- 本表只保存 metadata：original_filename 仅用于展示 / Content-Disposition，绝不参与文件路径（防 path traversal）。
-- 生命周期：submission 终态（APPROVE/REJECT/CANCEL）同事务删除本表行，commit 后 best-effort 清理物理文件
-- （跨表引用计数：hall_of_fame_record + 本表均无引用才删；失败仅 WARN 保留 orphan）。
-- 旧 PENDING（证据持久化功能上线前创建）无本表行 → 审核 UI 明确提示原始回放不可用，不伪造 replayAvailable。
create table hundred_battle_replay_evidence
(
    id                bigint generated by default as identity primary key,

    submission_id     bigint                   not null,
    -- 回放序号 1..5（submission + slot 唯一，一个 submission 恰好 5 行由 service 单事务保证）
    slot              integer                  not null,
    -- 用户原始文件名（仅展示 / Content-Disposition；不参与路径）
    original_filename varchar(255)             not null,
    -- SHA-256 内容寻址 key（= 物理文件名 {sha256}.wotbreplay，服务端生成，不接收用户路径）
    sha256            varchar(64)              not null,
    file_size         bigint                   not null,
    arena_id          varchar(64)              not null,

    created_at        timestamp with time zone not null default now(),

    constraint uk_hundred_evidence_submission_slot unique (submission_id, slot),
    constraint ck_hundred_evidence_slot check (slot between 1 and 5),
    -- FK RESTRICT：submission 当前设计永不物理删除（状态迁移为主），显式禁止任何意外级联删除业务数据
    constraint fk_hundred_evidence_submission
        foreign key (submission_id) references hundred_battle_submission (id)
);

-- 终态清理引用计数：按 sha256 查无引用才删除物理文件
create index idx_hundred_evidence_sha256 on hundred_battle_replay_evidence (sha256);
