-- 排行榜 MVP: 单场成绩记录。
-- 一条记录 = 某玩家(仅录像者本人)在某场战斗中用某辆车打出的单场伤害成绩。
-- 去重键: (arena_id, account_id) —— 同一场 + 同一玩家唯一; 不同玩家/不同场各自成行。
create table leaderboard_record (
    id           bigint generated by default as identity primary key,

    arena_id     varchar(32)  not null,

    tank_id      bigint       not null,
    tank_name    varchar(100) not null,

    account_id   bigint       not null,
    nickname     varchar(100) not null,

    damage_dealt integer      not null,

    map_name     varchar(100),

    created_at   timestamp with time zone not null default now(),

    constraint uk_leaderboard_record_arena_player
        unique (arena_id, account_id)
);

create index idx_leaderboard_record_damage_dealt
    on leaderboard_record (damage_dealt desc);

create index idx_leaderboard_record_tank_damage
    on leaderboard_record (tank_id, damage_dealt desc);

create index idx_leaderboard_record_account
    on leaderboard_record (account_id);

create index idx_leaderboard_record_created_at
    on leaderboard_record (created_at desc);
