-- 名人堂「三环」人工审核排行榜。三环一经审核通过即为当前最终记录，不存在 SUPERSEDED。
-- claimed 与 approved 均保留：管理员 approve 不接收成绩，只把冻结的 claimed 快照写入 approved。
create table mark3_submission (
    id bigint generated by default as identity primary key,

    user_keycloak_id varchar(64) not null,
    vehicle_id bigint not null,
    vehicle_name varchar(100) not null,

    game_account_id_snapshot bigint not null,
    nickname_snapshot varchar(100) not null,

    claimed_battle_count integer not null,
    claimed_average_damage integer not null,
    claimed_win_rate numeric(5, 2) not null,

    approved_battle_count integer,
    approved_average_damage integer,
    approved_win_rate numeric(5, 2),

    status varchar(16) not null default 'PENDING',

    -- 临时私有审核资产；终态（CURRENT / REJECTED / CANCELLED / DELETED）事务内清空。
    proof_screenshot_first text,
    proof_screenshot_second text,

    replay_parse_ok boolean not null default true,
    replay_game_id_match boolean not null default true,
    replay_vehicle_match boolean not null default true,
    replay_distinct_battles boolean not null default true,

    submitted_at timestamp with time zone not null default now(),
    approved_at timestamp with time zone,
    approved_by varchar(64),

    rejected_at timestamp with time zone,
    rejected_by varchar(64),
    reject_reason varchar(64),
    reject_reason_text varchar(500),

    cancelled_at timestamp with time zone,

    deleted_at timestamp with time zone,
    deleted_by varchar(64),
    delete_reason varchar(64),
    delete_reason_text varchar(500),

    constraint ck_mark3_submission_status
        check (status in ('PENDING', 'CURRENT', 'REJECTED', 'CANCELLED', 'DELETED')),
    constraint ck_mark3_claimed_values
        check (claimed_battle_count > 0 and claimed_average_damage > 0
            and claimed_win_rate >= 0 and claimed_win_rate <= 100),
    constraint ck_mark3_approved_values
        check ((approved_battle_count is null and approved_average_damage is null and approved_win_rate is null)
            or (approved_battle_count > 0 and approved_average_damage > 0
                and approved_win_rate >= 0 and approved_win_rate <= 100))
);

-- 三环 CURRENT 存在时不能再有 PENDING；REJECTED / CANCELLED / DELETED 允许重试。
create unique index uk_mark3_submission_active_user_vehicle
    on mark3_submission (user_keycloak_id, vehicle_id)
    where status in ('PENDING', 'CURRENT');

-- 单车公开排行榜：三环场数越少越靠前；同分按审核时间、ID 稳定排序。
create index idx_mark3_submission_leaderboard
    on mark3_submission (vehicle_id, status, approved_battle_count, approved_at, id);

create index idx_mark3_submission_status
    on mark3_submission (status, submitted_at desc);

create index idx_mark3_submission_user
    on mark3_submission (user_keycloak_id, status, submitted_at desc);

-- 三环独立回放证据表，避免与 hundred_battle_replay_evidence 的外键/生命周期耦合。
create table mark3_replay_evidence (
    id bigint generated by default as identity primary key,
    submission_id bigint not null,
    slot integer not null,
    original_filename varchar(255) not null,
    sha256 varchar(64) not null,
    file_size bigint not null,
    arena_id varchar(64) not null,
    created_at timestamp with time zone not null default now(),

    constraint uk_mark3_evidence_submission_slot unique (submission_id, slot),
    constraint ck_mark3_evidence_slot check (slot between 1 and 5),
    constraint fk_mark3_evidence_submission
        foreign key (submission_id) references mark3_submission (id)
);

create index idx_mark3_evidence_sha256 on mark3_replay_evidence (sha256);
