-- Tournament-specific snapshots; existing migration history is immutable.
CREATE TABLE tournament_event (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 year INTEGER NOT NULL CHECK (year BETWEEN 2000 AND 2100),
 region VARCHAR(16) NOT NULL CHECK (region IN ('CN','ASIA','EU','NA')),
 season VARCHAR(16) NOT NULL CHECK (season IN ('SPRING','SUMMER','AUTUMN','WINTER','FIRE_CUP')),
 round_count INTEGER NOT NULL CHECK (round_count BETWEEN 4 AND 5),
 days_per_round INTEGER NOT NULL CHECK (days_per_round BETWEEN 2 AND 3),
 day_labels JSONB NOT NULL, config_locked BOOLEAN NOT NULL DEFAULT FALSE,
 version BIGINT NOT NULL DEFAULT 0, UNIQUE(year, region, season)
);
CREATE TABLE tournament_rule (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 event_id BIGINT NOT NULL REFERENCES tournament_event(id),
 round_number INTEGER NOT NULL CHECK (round_number BETWEEN 1 AND 5),
 rules_version BIGINT NOT NULL DEFAULT 0, days JSONB NOT NULL,
 UNIQUE(event_id, round_number)
);
CREATE TABLE tournament_clan (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 event_id BIGINT NOT NULL REFERENCES tournament_event(id), clan_tag VARCHAR(32) NOT NULL,
 UNIQUE(event_id, clan_tag)
);
CREATE TABLE tournament_day (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 event_id BIGINT NOT NULL REFERENCES tournament_event(id),
 round_number INTEGER NOT NULL CHECK (round_number BETWEEN 1 AND 5),
 day_number INTEGER NOT NULL CHECK (day_number BETWEEN 1 AND 3),
 expected_group_count INTEGER CHECK (expected_group_count BETWEEN 1 AND 10000),
 draft_groups JSONB, published_groups JSONB, cleared_clans JSONB NOT NULL DEFAULT '[]'::jsonb,
 correction BOOLEAN NOT NULL DEFAULT FALSE, correction_reason VARCHAR(500),
 correction_started_at TIMESTAMP WITH TIME ZONE,
 version BIGINT NOT NULL DEFAULT 0, publication_keys JSONB NOT NULL DEFAULT '[]'::jsonb,
 UNIQUE(event_id, round_number, day_number)
);
CREATE TABLE tournament_evidence (
 id VARCHAR(36) PRIMARY KEY, event_id BIGINT NOT NULL REFERENCES tournament_event(id),
 round_number INTEGER NOT NULL, day_number INTEGER NOT NULL,
 image_hash VARCHAR(64) NOT NULL CHECK (image_hash ~ '^[a-f0-9]{64}$'),
 content_type VARCHAR(32) NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX tournament_evidence_event_idx ON tournament_evidence(event_id);
CREATE TABLE tournament_audit (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 event_id BIGINT NOT NULL REFERENCES tournament_event(id),
 round_number INTEGER, day_number INTEGER, action VARCHAR(32) NOT NULL,
 actor VARCHAR(64) NOT NULL, reason VARCHAR(500), created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 before_state JSONB NOT NULL, after_state JSONB NOT NULL
);
CREATE INDEX tournament_audit_event_idx ON tournament_audit(event_id, id);
