-- V3: 陪练功能初始表结构。
-- boost_request: 用户提交的陪练需求/订单。
-- booster_profile: 打手档案(业务侧记录,非 Keycloak 用户)。
-- boost_request_assignment: 需求-打手分配记录(支持历史分配、同一需求仅一个活跃分配)。

-- ========== 1. 陪练需求/订单 ==========
create table boost_request (
    id                   bigint generated by default as identity primary key,

    requester_user_id    bigint,
    wotb_account_id      bigint,

    player_account_id    bigint,
    player_nickname      varchar(100),

    region               varchar(32)  not null default 'CN',
    request_type         varchar(64)  not null,
    target_description   text         not null,

    budget_range         varchar(64),
    contact_type         varchar(32)  not null,
    contact_value        varchar(255) not null,
    available_time       text,
    remark               text,

    status               varchar(32)  not null default 'NEW',
    admin_note           text,

    created_at           timestamp with time zone not null default now(),
    updated_at           timestamp with time zone not null default now()
);

create index idx_boost_request_status
    on boost_request(status);

create index idx_boost_request_created_at
    on boost_request(created_at);

create index idx_boost_request_requester_user_id
    on boost_request(requester_user_id);

create index idx_boost_request_player_account_id
    on boost_request(player_account_id);

-- ========== 2. 打手档案 ==========
create table booster_profile (
    id            bigint generated by default as identity primary key,

    nickname      varchar(100) not null,
    level         varchar(32)  not null,

    available     boolean      not null default true,
    status        varchar(32)  not null default 'ACTIVE',

    contact_type  varchar(32),
    contact_value varchar(255),

    specialties   text,
    description   text,

    created_at    timestamp with time zone not null default now(),
    updated_at    timestamp with time zone not null default now()
);

create index idx_booster_profile_available
    on booster_profile(available);

create index idx_booster_profile_status
    on booster_profile(status);

-- ========== 3. 需求-打手分配记录(历史表) ==========
create table boost_request_assignment (
    id            bigint generated by default as identity primary key,

    request_id    bigint not null,
    booster_id    bigint not null,

    status        varchar(32) not null default 'ASSIGNED',

    assigned_at   timestamp with time zone not null default now(),
    unassigned_at timestamp with time zone,

    note          text,

    created_at    timestamp with time zone not null default now(),
    updated_at    timestamp with time zone not null default now(),

    constraint fk_boost_request_assignment_request
        foreign key (request_id)
        references boost_request(id)
        on delete cascade,

    constraint fk_boost_request_assignment_booster
        foreign key (booster_id)
        references booster_profile(id)
);

create index idx_boost_request_assignment_request_id
    on boost_request_assignment(request_id);

create index idx_boost_request_assignment_booster_id
    on boost_request_assignment(booster_id);

create index idx_boost_request_assignment_status
    on boost_request_assignment(status);

-- 按打手查活跃分配
create index idx_boost_request_assignment_booster_active
    on boost_request_assignment(booster_id)
    where unassigned_at is null;

-- 同一需求最多一个活跃分配
create unique index uq_boost_request_active_assignment
    on boost_request_assignment(request_id)
    where unassigned_at is null;
