-- V9: Player-submitted booster qualification applications.

CREATE TABLE booster_application (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    keycloak_user_id     VARCHAR(64)  NOT NULL,
    user_profile_id      BIGINT       NOT NULL,

    wotb_account_id      BIGINT       NOT NULL,
    wotb_nickname        VARCHAR(100) NOT NULL,
    wotb_server          VARCHAR(32)  NOT NULL DEFAULT 'CN',

    overall_stats_image  TEXT         NOT NULL,
    vehicle_stats_image  TEXT         NOT NULL,

    requested_level      VARCHAR(32)  NOT NULL,
    qq                   VARCHAR(64)  NOT NULL,
    wechat               VARCHAR(64),
    availability_tier    VARCHAR(64)  NOT NULL,
    daily_time_window    VARCHAR(255) NOT NULL,
    self_assessment      TEXT,

    status               VARCHAR(32)  NOT NULL DEFAULT 'NEW',
    admin_note           TEXT,
    approved_booster_id  BIGINT,
    reviewed_by          VARCHAR(64),
    reviewed_at          TIMESTAMP WITH TIME ZONE,

    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    CONSTRAINT fk_booster_application_booster
        FOREIGN KEY (approved_booster_id)
        REFERENCES booster_profile(id)
);

CREATE INDEX idx_booster_application_keycloak_user_id
    ON booster_application(keycloak_user_id);

CREATE INDEX idx_booster_application_status
    ON booster_application(status);

CREATE INDEX idx_booster_application_created_at
    ON booster_application(created_at);

CREATE UNIQUE INDEX uq_booster_application_open
    ON booster_application(keycloak_user_id)
    WHERE status IN ('NEW', 'REVIEWING');

CREATE UNIQUE INDEX IF NOT EXISTS uq_booster_profile_keycloak_user_id
    ON booster_profile(keycloak_user_id)
    WHERE keycloak_user_id IS NOT NULL;
