name: deploy

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "20m"
    max-file: "3"

services:
  health-probe:
    image: curlimages/curl:8.12.1
    entrypoint: ["curl"]
    restart: "no"
    logging: *default-logging


networks:
  default:
    name: wotb_tx_internal
    ipam:
      config:
        - subnet: 172.29.0.0/16
