name: deploy

include:
  - path: common.compose.yml
  - path: business-postgres.compose.yml
  - path: keycloak-postgres.compose.yml
  - path: rabbitmq.compose.yml
  - path: keycloak.compose.yml
  - path: frontend.compose.yml
  - path: business-api.compose.yml
  - path: caddy.compose.yml
  - path: alloy-tx.compose.yml
