package com.wotb.web.user.enums;

public enum UserNotificationType {
    BOOST_REQUEST_ASSIGNED,
    BOOST_ASSIGNMENT_RECEIVED,
    BOOST_ASSIGNMENT_ACCEPTED,
    BOOST_ASSIGNMENT_IN_PROGRESS,
    BOOST_ASSIGNMENT_PENDING_CONFIRM,
    BOOST_ASSIGNMENT_COMPLETED,
    BOOST_ASSIGNMENT_DECLINED,
    BOOST_ASSIGNMENT_CANCELLED,
    BOOST_ASSIGNMENT_EXCEPTION,
    BOOST_REQUEST_REJECTED,
    BOOSTER_APPLICATION_APPROVED,
    BOOSTER_APPLICATION_REJECTED
}
